#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct. 

echo "Github Source Branch: $SOURCE_BRANCH"
echo "Image Name: $IMAGE_NAME"

if [ -z "${DOCKER_REPO}" ]; then
  DOCKER_REPO=`echo $IMAGE_NAME |  sed 's/:.*//'`
fi

if [ -z "${SOURCE_REPO}" ]; then
  SOURCE_REPO=$DOCKER_REPO
fi

if [ -z "${SOURCE_IMAGE}" ]; then
  SOURCE_IMAGE=rocker/shiny
  echo "SOURCE_IMAGE not defined, using default value: $SOURCE_IMAGE"
fi

if [ -z "${SOURCE_TAG}" ]; then
  SOURCE_TAG=`echo $IMAGE_NAME | sed -n 's/^.*\://p'`
fi

echo "Source Docker Image: $SOURCE_IMAGE:$SOURCE_TAG"

docker build --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  --build-arg VERSION=0.1 \
  --build-arg DOCKER_IMAGE=$IMAGE_NAME \
  --build-arg SOURCE_REPO=$SOURCE_REPO \
  --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
  --build-arg SOURCE_COMMIT=$SOURCE_COMMIT \
  --build-arg SOURCE_IMAGE=$SOURCE_IMAGE \
  --build-arg SOURCE_TAG=$SOURCE_TAG \
  -t $IMAGE_NAME .
fi