#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct. 

echo "Source Branch: $SOURCE_BRANCH"
echo "Image Name: $IMAGE_NAME"

if [ -z "${DOCKER_REPO}" ]; then
  DOCKER_REPO=`echo $IMAGE_NAME |  sed 's/:.*//'`
fi

if [ -z "${PACKAGE_LIST}" ]; then
  PACKAGE_LIST=`echo $DOCKER_REPO | sed -n 's/^.*\///p'`
fi

docker build --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  --build-arg VERSION=0.1 \
  --build-arg DOCKER_IMAGE=$IMAGE_NAME \
  --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
  --build-arg SOURCE_COMMIT=$SOURCE_COMMIT \
  -t $IMAGE_NAME .
