#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct. 

echo "Github Source Branch: $SOURCE_BRANCH"
echo "Image Name: $IMAGE_NAME"

if [ -z "${DOCKER_REPO}" ]; then
  DOCKER_REPO=`echo $IMAGE_NAME |  sed 's/:.*//'`
fi

if [ -z "${SOURCE_REPO}" ]; then
  SOURCE_REPO=$DOCKER_REPO
fi

if [ -z "${SOURCE_IMAGE}" ]; then
  SOURCE_IMAGE=rocker/shiny
  echo "SOURCE_IMAGE not defined, using default value: $SOURCE_IMAGE"
fi

if [ -z "${SOURCE_TAG}" ]; then
  SOURCE_TAG=`echo $IMAGE_NAME | sed -n 's/^.*\://p'`
fi


if [ -z "${PACKAGE_LIST}" ]; then
  PACKAGE_LIST=`echo $DOCKER_REPO | sed -n 's/^.*\///p'`
fi

if [ -f "./package_lists/$PACKAGE_LIST/REQUIRED_PACKAGES.csv" ]  && [ -f "./package_lists/$PACKAGE_LIST/REQUIRED_PACKAGES_PLUS.csv" ]; then
  printf "using $PACKAGE_LIST package lists"; 
  if [ -z "${REQUIRED_PACKAGES}" ]; then REQUIRED_PACKAGES=`cat ./package_lists/$PACKAGE_LIST/REQUIRED_PACKAGES.csv` ; fi
  if [ -z "${REQUIRED_PACKAGES_PLUS}" ]; then REQUIRED_PACKAGES_PLUS=`cat ./package_lists/$PACKAGE_LIST/REQUIRED_PACKAGES_PLUS.csv` ; fi
else
  printf "using default package lists"; 
  if [ -z "${REQUIRED_PACKAGES}" ]; then REQUIRED_PACKAGES=`cat ./package_lists/default/REQUIRED_PACKAGES.csv` ; fi
  if [ -z "${REQUIRED_PACKAGES_PLUS}" ]; then REQUIRED_PACKAGES_PLUS=`cat ./package_lists/default/REQUIRED_PACKAGES_PLUS.csv` ; fi
fi

echo "R Package to be installed: $REQUIRED_PACKAGES"
echo "R Packages to be installed along with dependencies and suggestions: $REQUIRED_PACKAGES_PLUS"

echo "Source Docker Image: $SOURCE_IMAGE:$SOURCE_TAG"

docker build --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  --build-arg VERSION=0.1 \
  --build-arg DOCKER_IMAGE=$IMAGE_NAME \
  --build-arg SOURCE_REPO=$SOURCE_REPO \
  --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
  --build-arg SOURCE_COMMIT=$SOURCE_COMMIT \
  --build-arg SOURCE_IMAGE=$SOURCE_IMAGE \
  --build-arg SOURCE_TAG=$SOURCE_TAG \
  --build-arg DISCOVER_PACKAGES=$DISCOVER_PACKAGES \
  --build-arg REQUIRED_PACKAGES=$REQUIRED_PACKAGES \
  --build-arg DEPENDENCY_INSTALL=$DEPENDENCY_INSTALL \
  -t $IMAGE_NAME .
